import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalAuthFetch from "@/components/GlobalAuthFetch";
import GuestAuthInit from "@/components/GuestAuthInit";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "assistant-ui Starter App",
  description: "Generated by create-assistant-ui",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 自动处理鉴权失效：401/403 时清理登录态 */}
        <GlobalAuthFetch />
        {/* 若无登录态则尝试初始化访客账号 */}
        <GuestAuthInit />
        {children}
      </body>
    </html>
  );
}
